use std::io::Write;
use std::path::{Path, PathBuf};

use crate::{known_agent_profile_catalog, CliError};

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SetupAgent {
    Codex,
    Claude,
    OpenClaw,
}

pub struct ProfileSetupRequest {
    pub agent: SetupAgent,
    pub workspace: PathBuf,
    pub protect_secrets: bool,
}

pub fn default_setup_output(agent: SetupAgent) -> PathBuf {
    PathBuf::from(format!("warder-{}.toml", setup_agent_slug(agent)))
}

pub fn write_profile_setup_config(
    output: impl Into<PathBuf>,
    request: &ProfileSetupRequest,
    force: bool,
) -> Result<String, CliError> {
    let output = output.into();
    let config = render_profile_setup_config(request)?;
    if force {
        std::fs::write(&output, config).map_err(|error| CliError {
            message: format!(
                "failed to write setup config '{}': {error}",
                output.display()
            ),
        })?;
    } else {
        let mut file = std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&output)
            .map_err(|error| CliError {
                message: format!(
                    "failed to create setup config '{}': {error}",
                    output.display()
                ),
            })?;
        file.write_all(config.as_bytes())
            .map_err(|error| CliError {
                message: format!(
                    "failed to write setup config '{}': {error}",
                    output.display()
                ),
            })?;
    }
    Ok(format!(
        "wrote {} setup config: {}\nnext: warder explain --config {}\nthen: warder dry-run --config {} --agent {} -- {}",
        setup_agent_label(request.agent),
        output.display(),
        shell_quote(&output.display().to_string()),
        shell_quote(&output.display().to_string()),
        setup_agent_profile_id(request.agent),
        setup_agent_command_name(request.agent),
    ))
}

pub fn render_profile_setup_config(request: &ProfileSetupRequest) -> Result<String, CliError> {
    if !request.protect_secrets {
        return Err(CliError {
            message: "setup currently requires --protect-secrets so the generated policy has an explicit protected zone".to_string(),
        });
    }
    let workspace = normalize_setup_path(&request.workspace)?;
    let profile = setup_agent_profile_id(request.agent);
    let templates = known_agent_profile_catalog()
        .into_iter()
        .find(|entry| entry.id == profile)
        .map(|entry| entry.template.recommended_protected_paths)
        .unwrap_or_default();
    let protected_paths = templates
        .iter()
        .map(|template| expand_template_path(template.path))
        .collect::<Result<Vec<_>, _>>()?;
    if protected_paths.is_empty() {
        return Err(CliError {
            message: format!(
                "{} setup could not find any default protected paths",
                setup_agent_label(request.agent)
            ),
        });
    }
    let protected_paths = protected_paths
        .iter()
        .map(|path| toml_string(&path.display().to_string()))
        .collect::<Vec<_>>()
        .join(", ");
    Ok(format!(
        "[enforcement]\n\
landlock = \"best-effort\"\n\
cgroups = \"best-effort\"\n\
writable-roots = [{workspace}]\n\n\
[network]\n\
journal = true\n\n\
[[zones]]\n\
id = \"default-secrets\"\n\
name = \"Default Secret Paths\"\n\
description = \"Generated by warder setup; review paths before using for sensitive work.\"\n\
paths = [{protected_paths}]\n\
write_policy = \"deny\"\n\
# Read protection is experimental and off by default. Enable read-deny only\n\
# after configuring disjoint enforcement.readable-roots for the agent.\n\
read-deny = false\n\
snapshot = \"disabled\"\n\n\
[[agents]]\n\
id = {agent_id}\n\
label = {agent_label}\n\
command = {agent_command}\n\
profile = {agent_profile}\n",
        workspace = toml_string(&workspace.display().to_string()),
        agent_id = toml_string(profile),
        agent_label = toml_string(setup_agent_label(request.agent)),
        agent_command = toml_string(setup_agent_command_name(request.agent)),
        agent_profile = toml_string(profile),
    ))
}

pub fn setup_agent_from_str(value: &str) -> Option<SetupAgent> {
    match value {
        "codex" | "codex-cli" => Some(SetupAgent::Codex),
        "claude" | "claude-code" => Some(SetupAgent::Claude),
        "openclaw" | "openclaw-agent" => Some(SetupAgent::OpenClaw),
        _ => None,
    }
}

pub fn setup_agent_label(agent: SetupAgent) -> &'static str {
    match agent {
        SetupAgent::Codex => "Codex CLI",
        SetupAgent::Claude => "Claude Code",
        SetupAgent::OpenClaw => "OpenClaw",
    }
}

fn setup_agent_slug(agent: SetupAgent) -> &'static str {
    match agent {
        SetupAgent::Codex => "codex",
        SetupAgent::Claude => "claude",
        SetupAgent::OpenClaw => "openclaw",
    }
}

pub fn setup_agent_profile_id(agent: SetupAgent) -> &'static str {
    match agent {
        SetupAgent::Codex => "codex-cli",
        SetupAgent::Claude => "claude-code",
        SetupAgent::OpenClaw => "openclaw-agent",
    }
}

pub fn setup_agent_command_name(agent: SetupAgent) -> &'static str {
    match agent {
        SetupAgent::Codex => "codex",
        SetupAgent::Claude => "claude",
        SetupAgent::OpenClaw => "openclaw",
    }
}

fn normalize_setup_path(path: &Path) -> Result<PathBuf, CliError> {
    if path.is_absolute() {
        return Ok(path.to_path_buf());
    }
    std::env::current_dir()
        .map(|current_dir| current_dir.join(path))
        .map_err(|error| CliError {
            message: format!("failed to resolve current directory for setup config: {error}"),
        })
}

fn expand_template_path(path: &str) -> Result<PathBuf, CliError> {
    if let Some(rest) = path.strip_prefix("$HOME/") {
        let home = std::env::var_os("HOME").ok_or_else(|| CliError {
            message: "setup with --protect-secrets requires HOME for default secret paths"
                .to_string(),
        })?;
        return Ok(PathBuf::from(home).join(rest));
    }
    if path == "$HOME" {
        let home = std::env::var_os("HOME").ok_or_else(|| CliError {
            message: "setup with --protect-secrets requires HOME for default secret paths"
                .to_string(),
        })?;
        return Ok(PathBuf::from(home));
    }
    Ok(PathBuf::from(path))
}

fn toml_string(value: &str) -> String {
    let mut quoted = String::from("\"");
    for character in value.chars() {
        match character {
            '\\' => quoted.push_str("\\\\"),
            '"' => quoted.push_str("\\\""),
            '\n' => quoted.push_str("\\n"),
            '\r' => quoted.push_str("\\r"),
            '\t' => quoted.push_str("\\t"),
            other => quoted.push(other),
        }
    }
    quoted.push('"');
    quoted
}

fn shell_quote(value: &str) -> String {
    if value
        .bytes()
        .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'/' | b'.' | b'_' | b'-'))
    {
        value.to_string()
    } else {
        format!("'{}'", value.replace('\'', "'\"'\"'"))
    }
}
